import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { Sparkles, Zap, Film, Hash, ImageIcon, FolderOpen, TrendingUp, ArrowRight, Play } from 'lucide-react'

const features = [
  { icon: Zap, title: 'Viral Hook Generator', desc: 'AI-crafted opening hooks that stop the scroll and demand attention' },
  { icon: Film, title: 'Full Script Writing', desc: 'Complete scene-by-scene scripts optimized for your platform and style' },
  { icon: ImageIcon, title: 'AI Thumbnail Creator', desc: 'Eye-catching thumbnails generated by Gemini image AI in seconds' },
  { icon: Hash, title: 'Smart Hashtags & Captions', desc: 'Platform-specific hashtag sets and captions to maximize discoverability' },
  { icon: TrendingUp, title: 'Viral Score Prediction', desc: 'AI scores your content potential before you even press record' },
  { icon: FolderOpen, title: 'Script Management', desc: 'Organize scripts in projects, duplicate, edit, and manage your library' },
]

const stats = [
  { value: '10x', label: 'Faster Content Creation' },
  { value: '6+', label: 'Platforms Supported' },
  { value: '100%', label: 'AI-Powered' },
  { value: '7', label: 'Content Styles' },
]

const platforms = ['Instagram', 'YouTube', 'TikTok', 'LinkedIn', 'Twitter/X', 'Facebook']

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-[#0a0a0f] relative overflow-hidden">
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        <div className="absolute top-0 left-1/4 w-96 h-96 bg-violet-600/10 rounded-full blur-3xl" />
        <div className="absolute top-1/3 right-1/4 w-80 h-80 bg-purple-600/8 rounded-full blur-3xl" />
        <div className="absolute bottom-1/4 left-1/3 w-64 h-64 bg-blue-600/8 rounded-full blur-3xl" />
      </div>

      <nav className="relative z-10 border-b border-white/5 backdrop-blur-xl bg-black/20">
        <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-violet-500 to-purple-600 flex items-center justify-center">
              <Sparkles className="w-4 h-4 text-white" />
            </div>
            <span className="text-lg font-bold text-white">ReelForge <span className="text-violet-400">AI</span></span>
          </div>
          <div className="flex items-center gap-3">
            <Link href="/login">
              <Button variant="ghost" size="sm">Sign In</Button>
            </Link>
            <Link href="/signup">
              <Button variant="gradient" size="sm">Get Started Free</Button>
            </Link>
          </div>
        </div>
      </nav>

      <section className="relative z-10 pt-24 pb-16 px-6 text-center">
        <div className="max-w-4xl mx-auto">
          <div className="inline-flex items-center gap-2 rounded-full border border-violet-500/30 bg-violet-500/10 px-4 py-2 text-sm text-violet-300 mb-8">
            <Sparkles className="w-4 h-4" />
            Powered by Google Gemini AI
          </div>
          <h1 className="text-5xl md:text-7xl font-bold text-white mb-6 leading-tight">
            Create Viral Content<br />
            <span className="gradient-text">10x Faster</span>
          </h1>
          <p className="text-xl text-white/50 mb-10 max-w-2xl mx-auto leading-relaxed">
            Generate scripts, hooks, captions, hashtags, and AI thumbnails for Instagram, YouTube, TikTok and more — all in one platform.
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 mb-16">
            <Link href="/signup">
              <Button variant="gradient" size="xl" className="w-full sm:w-auto gap-2">
                Start Creating Free <ArrowRight className="w-5 h-5" />
              </Button>
            </Link>
            <Link href="/login">
              <Button variant="outline" size="xl" className="w-full sm:w-auto gap-2">
                <Play className="w-5 h-5" /> Sign In
              </Button>
            </Link>
          </div>
          <div className="flex flex-wrap justify-center gap-2">
            {platforms.map(p => (
              <span key={p} className="px-3 py-1 rounded-full text-xs font-medium border border-white/10 bg-white/5 text-white/60">{p}</span>
            ))}
          </div>
        </div>
      </section>

      <section className="relative z-10 py-16 px-6">
        <div className="max-w-4xl mx-auto grid grid-cols-2 md:grid-cols-4 gap-8">
          {stats.map(({ value, label }) => (
            <div key={label} className="text-center">
              <div className="text-3xl md:text-4xl font-bold gradient-text mb-2">{value}</div>
              <div className="text-sm text-white/40">{label}</div>
            </div>
          ))}
        </div>
      </section>

      <section className="relative z-10 py-20 px-6">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Everything You Need to Go Viral</h2>
            <p className="text-white/40 max-w-xl mx-auto">A complete AI-powered creator toolkit — from ideation to publishing</p>
          </div>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {features.map(({ icon: Icon, title, desc }) => (
              <div key={title} className="group rounded-2xl border border-white/8 bg-white/3 p-6 hover:border-violet-500/30 hover:bg-violet-500/5 transition-all duration-300">
                <div className="w-12 h-12 rounded-xl bg-violet-500/15 flex items-center justify-center mb-4 group-hover:bg-violet-500/25 transition-colors">
                  <Icon className="w-6 h-6 text-violet-400" />
                </div>
                <h3 className="text-lg font-semibold text-white mb-2">{title}</h3>
                <p className="text-sm text-white/40 leading-relaxed">{desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="relative z-10 py-20 px-6">
        <div className="max-w-2xl mx-auto text-center">
          <div className="rounded-3xl border border-violet-500/20 bg-gradient-to-br from-violet-500/10 to-purple-500/5 p-12 backdrop-blur-sm">
            <Sparkles className="w-12 h-12 text-violet-400 mx-auto mb-4" />
            <h2 className="text-3xl font-bold text-white mb-4">Ready to Go Viral?</h2>
            <p className="text-white/50 mb-8">Start generating AI-powered scripts and thumbnails for free.</p>
            <Link href="/signup">
              <Button variant="gradient" size="xl">
                Create Your First Script <ArrowRight className="w-5 h-5" />
              </Button>
            </Link>
          </div>
        </div>
      </section>

      <footer className="relative z-10 border-t border-white/5 py-8 px-6">
        <div className="max-w-7xl mx-auto flex flex-col md:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <div className="w-6 h-6 rounded-md bg-gradient-to-br from-violet-500 to-purple-600 flex items-center justify-center">
              <Sparkles className="w-3 h-3 text-white" />
            </div>
            <span className="text-sm text-white/40">ReelForge AI — Built for creators</span>
          </div>
          <div className="text-sm text-white/30">Powered by Google Gemini</div>
        </div>
      </footer>
    </div>
  )
}
